image: node:4.2.2

cache:
  paths:
  - node_modules/

stages:
  - test

before_script:
  - echo "INSTALL:"
  - npm install

after_script:
  - echo "DONE!"

Tests:
  stage: test
  script:
   - echo "TESTS:"
   - npm test
