image: node:4.2.2

cache:
  paths:
  - node_modules/

stages:
  - test

before_script:
  - echo "INSTALL:"
  - npm install --only=dev

after_script:
  - echo "DONE!"

Test:
  stage: test
  script:
   - echo "TESTS:"
   - npm test

Bithound:
  stage: test
  script:
    - echo "BITHOUND:"
    - echo "Removed momentarily"
#   - node_modules/.bin/bithound check git@github.com:Cornet-JS/Cornet.JS.git
