image: node:4.2.2

cache:
  paths:
  - node_modules/

stages:
  - test
  - dist

before_script:
  - npm install

test:
  stage: test
  script:
    - echo "Test files"
    - node_modules/.bin/xo cornet.js

dist:
  stage: dist
   artifacts:
    paths:
      - dist/
  script:
    - echo "Make directories"
    - mkdir dist
    - mkdir dist/themes
    - echo "Copy files"
    - cp -v CHANGELOG.md cornet.js LICENSE package.json README.md /dist
    - cp -v themes/. /dist/themes
    - echo "Minify files"
    - shopt -s nullglob
    - node_modules/.bin/uglifyjs cornet.js --ie8 --verbose --output dist/cornet.min.js
    - for f in /dist/themes/*.css
    - do
    -   echo "Minifying $f"
    -   node_modules/.bin/clean-css --debug --compatability --output "dist/$f" "$f"
    - done
